name: OctoDNS Changelog
on:
  pull_request:
  workflow_dispatch:

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.load.outputs.json }}
    steps:
    - uses: actions/checkout@v4
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Changelog Check
        run: |
          ./script/changelog check
